---
- name: Testing andrewrothstein.olm
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'olm --version'
      ansible.builtin.command: /usr/local/bin/olm --version
      changed_when: false
      register: olm_test_version
    - name: Output from 'olm --version'
      ansible.builtin.debug:
        msg: '{{ olm_test_version.stdout }}'
