---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/olm --version
      register: olm_test_version
    - name: olm --version
      debug:
        msg: '{{ olm_test_version.stdout }}'
